Generate blessed version of consul
[#104050238]

Signed-off-by: Joseph Palermo <jpalermo@pivotal.io>

diff --git a/scripts/generate_blessed_versions b/scripts/generate_blessed_versions
--- a/scripts/generate_blessed_versions
+++ b/scripts/generate_blessed_versions
@@ -16,14 +16,15 @@ OUTPUT_DIR=${SCRIPT_DIR}/../outputs/create_release
 rm -rf ${OUTPUT_DIR}
 mkdir -p ${OUTPUT_DIR}
 
-if [ $# -ne 3 ]; then
-  echo "Usage: create_releases PATH_TO_CF_RELEASE PATH_TO_ETCD_RELEASE PATH_TO_CONSUL_RELEASE"
+if [ $# -ne 4 ]; then
+  echo "Usage: create_releases PATH_TO_CF_RELEASE PATH_TO_ETCD_RELEASE PATH_TO_CONSUL_RELEASE PATH_TO_CONSUL_RELEASE"
   exit 1
 fi
 
 STEMCELL_PATH=$1
 CF_RELEASE_PATH=$2
 ETCD_RELEASE_PATH=$3
+CONSUL_RELEASE_PATH=$4
 
 if [ ! -e ${STEMCELL_PATH} ]; then
   echo "PATH_TO_STEMCELL is invalid"
@@ -40,6 +41,11 @@ if [ ! -e ${ETCD_RELEASE_PATH} ]; then
   exit 1
 fi
 
+if [ ! -e ${CONSUL_RELEASE_PATH} ]; then
+  echo "PATH_TO_CONSUL_RELEASE is invalid"
+  exit 1
+fi
+
 
 export BOSH_USE_BUNDLER=true
 
@@ -51,6 +57,8 @@ popd
 
 ETCD_VERSION=$(tar -x -O -f ${ETCD_RELEASE_PATH} ./release.MF | grep -E '^version:' | grep -o -E "[0-9.]*[0-9]")
 ETCD_SHA=$(sha1sum ${ETCD_RELEASE_PATH} | awk '{print $1;}')
+CONSUL_VERSION=$(tar -x -O -f ${CONSUL_RELEASE_PATH} ./release.MF | grep -E '^version:' | grep -o -E "[0-9.]*[0-9]")
+CONSUL_SHA=$(sha1sum ${CONSUL_RELEASE_PATH} | awk '{print $1;}')
 STEMCELL_VERSION=$(tar -xOf ${STEMCELL_PATH} stemcell.MF | grep version | head -1 | grep -o -E "[0-9.]*[0-9]")
 STEMCELL_NAME=$(tar -xOf ${STEMCELL_PATH} stemcell.MF | grep name | head -1 | awk '{print $2;}')
 STEMCELL_SHA1=$(sha1sum ${STEMCELL_PATH} | awk '{print $1;}')
@@ -71,6 +79,12 @@ cat > $CF_DEPLOYMENT_DIR/blessed_versions.json <<EOF
       "version": "${ETCD_VERSION}",
       "sha1": "${ETCD_SHA}",
       "url": "https://bosh.io/d/github.com/cloudfoundry-incubator/etcd-release?v=${ETCD_VERSION}"
+    },
+    {
+      "name": "consul",
+      "version": "${CONSUL_VERSION}",
+      "sha1": "${CONSUL_SHA}",
+      "url": "https://bosh.io/d/github.com/cloudfoundry-incubator/consul-release?v=${CONSUL_VERSION}"
     }
   ],
   "stemcells": {
